### ISSUE TITLE
Page Analytics [ 3 days ]

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/forestplanner#204]
Perhaps https://mixpanel.com/segmentation/ instead of Google Analytics?

**Comment by d-diaz** [comment]
I would love to implement [MixPanel](https://mixpanel.com/) tracking to at least figure out how many people make it to each "page" (property mapping, stand mapping, forest typing, and different scenario screens). @rhodges, please coordinate with @willthemoor as needed.

**Comment by willthemoor** [comment]
I'm all for Mixpanel but if time counts, Ryan could get GA page tracking going pretty quickly since the main pipe to GA is already set up. 

For views we want to track, add this GA snippet wherever knockout does the view switching.

like:
```
ga('send', 'pageview', '/Stand Mapping');
```

I built a rudimentary router for the main views here: https://github.com/Ecotrust/forestplanner/blob/9f44a4a2a4020f452986ae49669c71895143f033/media/common/js/hash_routing.js#L31

Sticking that ga snippet into each switch:case will cover the main tab views. For specific sub views (like scenario building vs scenarios, generally) the ga snippet will need to be inserted in the random bits of code that does the view switching. Oh, Knockout. 

For reporting purposes later on, mimic paths for anything that's nested. In particular, this will make the Content Drilldown and User Journey reports in GA usable.

For example:
```
# Main Scenario Page
ga('send', 'pageview', '/Scenarios');

# Scenario Building/Editing
ga('send', 'pageview', '/Scenarios/Editing');

# Scenario Building/Editing Step 2
ga('send', 'pageview', '/Scenarios/Editing/Step 2);

# Scenario Building/Editing Adding a Prescription
ga('send', 'pageview', '/Scenarios/Editing/Step 2/Add Prescription');

```

https://developers.google.com/analytics/devguides/collection/analyticsjs/pages for reference.
