### ISSUE TITLE
Carbon groups references list

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/forestplanner#390]
- top right dropdown nav
  <img width="256" alt="Screen Shot 2019-03-25 at 6 18 19 PM" src="https://user-images.githubusercontent.com/2632164/54964680-9e9fbc00-4f2a-11e9-8317-63602260b239.png">
  
-

**Comment by rhodges** [comment]
@dpollard - part of the migration strategy on my plate will be untangling which commits went into production and which were kept out. 
Since we developed "discovery" on top of master we will need to be careful not to merge everything into the production branch - I will be researching options to try to reset discovery's start commit/branch.
